### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ghost** [RocketLauncher21/website#1]
i know this is not the place to ask but can i have dll_patches because the link is down.

**Comment by voyageprofessor** [comment]
I found it but i have some issue, the script editor shows this only when im loading the project:
![image](https://github.com/RocketLauncher21/website/assets/161885678/233f78a0-423e-441e-8b3b-be7d27164e02)

**Comment by dky4** [comment]
No. Contact me on Discord or somewhere. Do not go to my fucking GitHub issues and to for this. I can't send it publicly.
